# This makefile is intended to build database of CPE Computer for
# CPE100 Project 2
#
# Created 17/12/2020 By 
# ID 6307050
# 

EXECUTABLES=database

all : $(EXECUTABLES)

Fmanager_modify_search.o : Fmanager_modify_search.c header.h
	gcc -c Fmanager_modify_search.c header.h

Fmanager_add.o : Fmanager_add.c header.h
	gcc -c Fmanager_add.c header.h

Fmanager_display.o : Fmanager_display.c header.h
	gcc -c Fmanager_display.c header.h

valid_main.o : valid_main.c header.h
	gcc -c valid_main.c

valid_sub.o : valid_sub.c header.h
	gcc -c valid_sub.c

userInterf.o : userInterf.c header.h
	gcc -c userInterf.c

database : userInterf.o valid_main.o valid_sub.o Fmanager_display.o Fmanager_add.o Fmanager_modify_search.o
	gcc -o database userInterf.o valid_main.o valid_sub.o Fmanager_display.o Fmanager_add.o Fmanager_modify_search.o


clean :
	-rm *.o
	-rm database