# This makefile is intended to build database of CPE Computer for
# CPE100 Project 2
#
# Created 17/12/2020 By 
# ID 6307050
# 

EXECUTABLES=database

all : $(EXECUTABLES)

Fmanager.o : Fmanager.c header.h
	gcc -c Fmanager.c

valid_main.o : valid_main.c header.h
	gcc -c valid_main.c

valid_sub.o : valid_sub.c header.h
	gcc -c valid_sub.c

userInterf.o : userInterf.c header.h
	gcc -c userInterf.c

database : userInterf.o valid_main.o valid_sub.o Fmanager.o
	gcc -o database userInterf.o valid_main.o valid_sub.o Fmanager.o


clean :
	-rm *.o
	-rm database